name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install pcl
      run: apt install libpcl-dev
    - name: mkdir build
      run: mkdir build 
    - name: cd build
      run: cd build
    - name: cmake ..
      run: cmake ..
    - name: make
      run: make
