name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install pcl
      run: sudo apt install libpcl-dev -y
    - name: mkdir build
      run: mkdir build 
    - name: cd build && cmake .. && make
      run: cd build && cmake .. && sudo make install
    
