name: MacOS build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: brew install pcl
      run: brew install pcl
    - name: brew install pcl
      run: brew install pcl
    - name: install PointClouds from source
      run: git clone https://github.com/PointCloudLibrary/pcl.git && cd pcl && mkdir build && cd build && cmake .. && make install
    - name: mkdir build && cd build && cmake .. && make install
      run: mkdir build && cd build && cmake .. && make install
    
